services:
  - type: web
    name: supermercado-api
    runtime: python
    rootDir: api
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: supermercado-db
          property: connectionString

databases:
  - name: supermercado-db
    databaseName: supermercado
    user: supermercado_user
    plan: free
